# fly.toml app configuration file generated for perfey on 2023-11-18T01:03:01+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "perfey"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
